version: '3.6'
# Deploys MongoDB with customization scripts and container
# usage:
# sudo docker-compose build
# sudo docker-compose up

services:
  mongodb:
    container_name: casino_db_mongo
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27018:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
